language: node_js
node_js:
  - 10.15
install: 
  - yarn 
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: f1d5d8f392b19a26a2c3104adf52d24a1d34d52c
  keep-history: true
  on:
    branch: master